/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Alumno
 */
export interface Alumno {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    rut: string;
    /**
     * 
     */
    username: string;
    /**
     * 
     */
    nombre: string;
    /**
     * 
     */
    apellido: string;
}

/**
 * Check if a given object implements the Alumno interface.
 */
export function instanceOfAlumno(value: object): value is Alumno {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rut' in value) || value['rut'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    if (!('apellido' in value) || value['apellido'] === undefined) return false;
    return true;
}

export function AlumnoFromJSON(json: any): Alumno {
    return AlumnoFromJSONTyped(json, false);
}

export function AlumnoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alumno {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rut': json['rut'],
        'username': json['username'],
        'nombre': json['nombre'],
        'apellido': json['apellido'],
    };
}

export function AlumnoToJSON(json: any): Alumno {
    return AlumnoToJSONTyped(json, false);
}

export function AlumnoToJSONTyped(value?: Alumno | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rut': value['rut'],
        'username': value['username'],
        'nombre': value['nombre'],
        'apellido': value['apellido'],
    };
}

