/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Alumno } from './Alumno';
import {
    AlumnoFromJSON,
    AlumnoFromJSONTyped,
    AlumnoToJSON,
    AlumnoToJSONTyped,
} from './Alumno';

/**
 * 
 * @export
 * @interface AlumnosResponse
 */
export interface AlumnosResponse {
    /**
     * 
     */
    data: Array<Alumno>;
}

/**
 * Check if a given object implements the AlumnosResponse interface.
 */
export function instanceOfAlumnosResponse(value: object): value is AlumnosResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AlumnosResponseFromJSON(json: any): AlumnosResponse {
    return AlumnosResponseFromJSONTyped(json, false);
}

export function AlumnosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlumnosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AlumnoFromJSON)),
    };
}

export function AlumnosResponseToJSON(json: any): AlumnosResponse {
    return AlumnosResponseToJSONTyped(json, false);
}

export function AlumnosResponseToJSONTyped(value?: AlumnosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(AlumnoToJSON)),
    };
}

