/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Aula } from './Aula';
import {
    AulaFromJSON,
    AulaFromJSONTyped,
    AulaToJSON,
    AulaToJSONTyped,
} from './Aula';

/**
 * 
 * @export
 * @interface AulaResponse
 */
export interface AulaResponse {
    /**
     * 
     */
    data: Aula;
}

/**
 * Check if a given object implements the AulaResponse interface.
 */
export function instanceOfAulaResponse(value: object): value is AulaResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AulaResponseFromJSON(json: any): AulaResponse {
    return AulaResponseFromJSONTyped(json, false);
}

export function AulaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AulaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AulaFromJSON(json['data']),
    };
}

export function AulaResponseToJSON(json: any): AulaResponse {
    return AulaResponseToJSONTyped(json, false);
}

export function AulaResponseToJSONTyped(value?: AulaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AulaToJSON(value['data']),
    };
}

