/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Aula } from './Aula';
import {
    AulaFromJSON,
    AulaFromJSONTyped,
    AulaToJSON,
    AulaToJSONTyped,
} from './Aula';

/**
 * 
 * @export
 * @interface AulasResponse
 */
export interface AulasResponse {
    /**
     * 
     */
    data: Array<Aula>;
}

/**
 * Check if a given object implements the AulasResponse interface.
 */
export function instanceOfAulasResponse(value: object): value is AulasResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AulasResponseFromJSON(json: any): AulasResponse {
    return AulasResponseFromJSONTyped(json, false);
}

export function AulasResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AulasResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AulaFromJSON)),
    };
}

export function AulasResponseToJSON(json: any): AulasResponse {
    return AulasResponseToJSONTyped(json, false);
}

export function AulasResponseToJSONTyped(value?: AulasResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(AulaToJSON)),
    };
}

