/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Aula
 */
export interface Aula {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    nombre: string;
}

/**
 * Check if a given object implements the Aula interface.
 */
export function instanceOfAula(value: object): value is Aula {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    return true;
}

export function AulaFromJSON(json: any): Aula {
    return AulaFromJSONTyped(json, false);
}

export function AulaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Aula {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nombre': json['nombre'],
    };
}

export function AulaToJSON(json: any): Aula {
    return AulaToJSONTyped(json, false);
}

export function AulaToJSONTyped(value?: Aula | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
    };
}

