/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdempotencyMeta
 */
export interface IdempotencyMeta {
    /**
     * 
     */
    idempotentReplay: boolean;
}

/**
 * Check if a given object implements the IdempotencyMeta interface.
 */
export function instanceOfIdempotencyMeta(value: object): value is IdempotencyMeta {
    if ((!('idempotentReplay' in (value as Record<string, any>)) && !('idempotent_replay' in (value as Record<string, any>))) || ((value as Record<string, any>)['idempotentReplay'] === undefined && (value as Record<string, any>)['idempotent_replay'] === undefined)) return false;
    return true;
}

export function IdempotencyMetaFromJSON(json: any): IdempotencyMeta {
    return IdempotencyMetaFromJSONTyped(json, false);
}

export function IdempotencyMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdempotencyMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotentReplay': json['idempotent_replay'],
    };
}

export function IdempotencyMetaToJSON(json: any): IdempotencyMeta {
    return IdempotencyMetaToJSONTyped(json, false);
}

export function IdempotencyMetaToJSONTyped(value?: IdempotencyMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idempotent_replay': value['idempotentReplay'],
    };
}

