/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdempotencyMeta } from './IdempotencyMeta';
import {
    IdempotencyMetaFromJSON,
    IdempotencyMetaFromJSONTyped,
    IdempotencyMetaToJSON,
    IdempotencyMetaToJSONTyped,
} from './IdempotencyMeta';
import type { InvitacionReplay } from './InvitacionReplay';
import {
    InvitacionReplayFromJSON,
    InvitacionReplayFromJSONTyped,
    InvitacionReplayToJSON,
    InvitacionReplayToJSONTyped,
} from './InvitacionReplay';

/**
 * 
 * @export
 * @interface InvitacionReplayResponse
 */
export interface InvitacionReplayResponse {
    /**
     * 
     */
    data: InvitacionReplay;
    /**
     * 
     */
    meta: IdempotencyMeta;
}

/**
 * Check if a given object implements the InvitacionReplayResponse interface.
 */
export function instanceOfInvitacionReplayResponse(value: object): value is InvitacionReplayResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function InvitacionReplayResponseFromJSON(json: any): InvitacionReplayResponse {
    return InvitacionReplayResponseFromJSONTyped(json, false);
}

export function InvitacionReplayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitacionReplayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': InvitacionReplayFromJSON(json['data']),
        'meta': IdempotencyMetaFromJSON(json['meta']),
    };
}

export function InvitacionReplayResponseToJSON(json: any): InvitacionReplayResponse {
    return InvitacionReplayResponseToJSONTyped(json, false);
}

export function InvitacionReplayResponseToJSONTyped(value?: InvitacionReplayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvitacionReplayToJSON(value['data']),
        'meta': IdempotencyMetaToJSON(value['meta']),
    };
}

