/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface Invitacion
 */
export interface Invitacion {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    rut: string;
    /**
     * 
     */
    username: string;
    /**
     * 
     */
    rol: InvitacionRolEnum;
    /**
     * 
     */
    expiraEn: Date;
    /**
     * 
     */
    urlActivacion?: string;
}


/**
 * @export
 */
export const InvitacionRolEnum = {
    Alumno: 'alumno',
    Profesor: 'profesor',
} as const;
export type InvitacionRolEnum = typeof InvitacionRolEnum[keyof typeof InvitacionRolEnum];


/**
 * Check if a given object implements the Invitacion interface.
 */
export function instanceOfInvitacion(value: object): value is Invitacion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('rut' in value) || value['rut'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('rol' in value) || value['rol'] === undefined) return false;
    if ((!('expiraEn' in (value as Record<string, any>)) && !('expira_en' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiraEn'] === undefined && (value as Record<string, any>)['expira_en'] === undefined)) return false;
    return true;
}

export function InvitacionFromJSON(json: any): Invitacion {
    return InvitacionFromJSONTyped(json, false);
}

export function InvitacionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invitacion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'rut': json['rut'],
        'username': json['username'],
        'rol': json['rol'],
        'expiraEn': (json['expira_en'] == null ? json['expira_en'] : parseDateTime(json['expira_en'])),
        'urlActivacion': json['url_activacion'] == null ? undefined : json['url_activacion'],
    };
}

export function InvitacionToJSON(json: any): Invitacion {
    return InvitacionToJSONTyped(json, false);
}

export function InvitacionToJSONTyped(value?: Invitacion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'rut': value['rut'],
        'username': value['username'],
        'rol': value['rol'],
        'expira_en': value['expiraEn'] == null ? value['expiraEn'] : serializeDateTime(value['expiraEn']),
        'url_activacion': value['urlActivacion'],
    };
}

