/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvitacionRequest
 */
export interface InvitacionRequest {
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    rut: string;
    /**
     * 
     */
    username: string;
    /**
     * 
     */
    rol: InvitacionRequestRolEnum;
}


/**
 * @export
 */
export const InvitacionRequestRolEnum = {
    Alumno: 'alumno',
    Profesor: 'profesor',
} as const;
export type InvitacionRequestRolEnum = typeof InvitacionRequestRolEnum[keyof typeof InvitacionRequestRolEnum];


/**
 * Check if a given object implements the InvitacionRequest interface.
 */
export function instanceOfInvitacionRequest(value: object): value is InvitacionRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('rut' in value) || value['rut'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('rol' in value) || value['rol'] === undefined) return false;
    return true;
}

export function InvitacionRequestFromJSON(json: any): InvitacionRequest {
    return InvitacionRequestFromJSONTyped(json, false);
}

export function InvitacionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitacionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'rut': json['rut'],
        'username': json['username'],
        'rol': json['rol'],
    };
}

export function InvitacionRequestToJSON(json: any): InvitacionRequest {
    return InvitacionRequestToJSONTyped(json, false);
}

export function InvitacionRequestToJSONTyped(value?: InvitacionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'rut': value['rut'],
        'username': value['username'],
        'rol': value['rol'],
    };
}

