/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Invitacion } from './Invitacion';
import {
    InvitacionFromJSON,
    InvitacionFromJSONTyped,
    InvitacionToJSON,
    InvitacionToJSONTyped,
} from './Invitacion';
import type { IdempotencyMeta } from './IdempotencyMeta';
import {
    IdempotencyMetaFromJSON,
    IdempotencyMetaFromJSONTyped,
    IdempotencyMetaToJSON,
    IdempotencyMetaToJSONTyped,
} from './IdempotencyMeta';

/**
 * 
 * @export
 * @interface InvitacionResponse
 */
export interface InvitacionResponse {
    /**
     * 
     */
    data: Invitacion;
    /**
     * 
     */
    meta: IdempotencyMeta;
}

/**
 * Check if a given object implements the InvitacionResponse interface.
 */
export function instanceOfInvitacionResponse(value: object): value is InvitacionResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function InvitacionResponseFromJSON(json: any): InvitacionResponse {
    return InvitacionResponseFromJSONTyped(json, false);
}

export function InvitacionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitacionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': InvitacionFromJSON(json['data']),
        'meta': IdempotencyMetaFromJSON(json['meta']),
    };
}

export function InvitacionResponseToJSON(json: any): InvitacionResponse {
    return InvitacionResponseToJSONTyped(json, false);
}

export function InvitacionResponseToJSONTyped(value?: InvitacionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvitacionToJSON(value['data']),
        'meta': IdempotencyMetaToJSON(value['meta']),
    };
}

