/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsuarioSesion
 */
export interface UsuarioSesion {
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    username: string;
    /**
     * 
     */
    nombre: string;
    /**
     * 
     */
    apellido: string;
    /**
     * 
     */
    rol: UsuarioSesionRolEnum;
}


/**
 * @export
 */
export const UsuarioSesionRolEnum = {
    Alumno: 'alumno',
    Profesor: 'profesor',
} as const;
export type UsuarioSesionRolEnum = typeof UsuarioSesionRolEnum[keyof typeof UsuarioSesionRolEnum];


/**
 * Check if a given object implements the UsuarioSesion interface.
 */
export function instanceOfUsuarioSesion(value: object): value is UsuarioSesion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    if (!('apellido' in value) || value['apellido'] === undefined) return false;
    if (!('rol' in value) || value['rol'] === undefined) return false;
    return true;
}

export function UsuarioSesionFromJSON(json: any): UsuarioSesion {
    return UsuarioSesionFromJSONTyped(json, false);
}

export function UsuarioSesionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsuarioSesion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'nombre': json['nombre'],
        'apellido': json['apellido'],
        'rol': json['rol'],
    };
}

export function UsuarioSesionToJSON(json: any): UsuarioSesion {
    return UsuarioSesionToJSONTyped(json, false);
}

export function UsuarioSesionToJSONTyped(value?: UsuarioSesion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'nombre': value['nombre'],
        'apellido': value['apellido'],
        'rol': value['rol'],
    };
}

