/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AlumnosResponse,
    AlumnosResponseFromJSON,
    AlumnosResponseToJSON,
} from '../models/AlumnosResponse';
import {
    type AulaResponse,
    AulaResponseFromJSON,
    AulaResponseToJSON,
} from '../models/AulaResponse';
import {
    type AulasResponse,
    AulasResponseFromJSON,
    AulasResponseToJSON,
} from '../models/AulasResponse';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface ObtenerAlumnosAulaRequest {
    /**
     * Identificador único del aula.
     */
    aulaId: number;
}

export interface ObtenerAulaRequest {
    /**
     * Identificador único del aula.
     */
    aulaId: number;
}

/**
 * 
 */
export class AulasApi extends runtime.BaseAPI {

    /**
     * Creates request options for obtenerAlumnosAula without sending the request
     */
    async obtenerAlumnosAulaRequestOpts(requestParameters: ObtenerAlumnosAulaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aulaId'] == null) {
            throw new runtime.RequiredError(
                'aulaId',
                'Required parameter "aulaId" was null or undefined when calling obtenerAlumnosAula().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/aulas/{aulaId}/alumnos`;
        urlPath = urlPath.replace('{aulaId}', encodeURIComponent(String(requestParameters['aulaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Devuelve los alumnos activos pertenecientes al aula indicada. 
     * Obtener los alumnos de un aula
     */
    async obtenerAlumnosAulaRaw(requestParameters: ObtenerAlumnosAulaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlumnosResponse>> {
        const requestOptions = await this.obtenerAlumnosAulaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlumnosResponseFromJSON(jsonValue));
    }

    /**
     * Devuelve los alumnos activos pertenecientes al aula indicada. 
     * Obtener los alumnos de un aula
     */
    async obtenerAlumnosAula(requestParameters: ObtenerAlumnosAulaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlumnosResponse> {
        const response = await this.obtenerAlumnosAulaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for obtenerAula without sending the request
     */
    async obtenerAulaRequestOpts(requestParameters: ObtenerAulaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aulaId'] == null) {
            throw new runtime.RequiredError(
                'aulaId',
                'Required parameter "aulaId" was null or undefined when calling obtenerAula().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/aulas/{aulaId}`;
        urlPath = urlPath.replace('{aulaId}', encodeURIComponent(String(requestParameters['aulaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Devuelve la información de un aula específica a la que pertenece el profesor autenticado. 
     * Obtener un aula
     */
    async obtenerAulaRaw(requestParameters: ObtenerAulaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AulaResponse>> {
        const requestOptions = await this.obtenerAulaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AulaResponseFromJSON(jsonValue));
    }

    /**
     * Devuelve la información de un aula específica a la que pertenece el profesor autenticado. 
     * Obtener un aula
     */
    async obtenerAula(requestParameters: ObtenerAulaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AulaResponse> {
        const response = await this.obtenerAulaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for obtenerAulas without sending the request
     */
    async obtenerAulasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/aulas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Devuelve las aulas activas asociadas al profesor autenticado. 
     * Obtener las aulas del profesor
     */
    async obtenerAulasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AulasResponse>> {
        const requestOptions = await this.obtenerAulasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AulasResponseFromJSON(jsonValue));
    }

    /**
     * Devuelve las aulas activas asociadas al profesor autenticado. 
     * Obtener las aulas del profesor
     */
    async obtenerAulas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AulasResponse> {
        const response = await this.obtenerAulasRaw(initOverrides);
        return await response.value();
    }

}
