/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type LoginRequest,
    LoginRequestFromJSON,
    LoginRequestToJSON,
} from '../models/LoginRequest';
import {
    type LoginResponse,
    LoginResponseFromJSON,
    LoginResponseToJSON,
} from '../models/LoginResponse';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface IniciarSesionRequest {
    /**
     * 
     */
    loginRequest: LoginRequest;
}

/**
 * 
 */
export class AutenticacinApi extends runtime.BaseAPI {

    /**
     * Creates request options for iniciarSesion without sending the request
     */
    async iniciarSesionRequestOpts(requestParameters: IniciarSesionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling iniciarSesion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        };
    }

    /**
     * Autentica a un usuario mediante su identificador y contraseña e inicia una sesión mediante una cookie PHPSESSID. 
     * Iniciar sesión
     */
    async iniciarSesionRaw(requestParameters: IniciarSesionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponse>> {
        const requestOptions = await this.iniciarSesionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
    }

    /**
     * Autentica a un usuario mediante su identificador y contraseña e inicia una sesión mediante una cookie PHPSESSID. 
     * Iniciar sesión
     */
    async iniciarSesion(requestParameters: IniciarSesionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponse> {
        const response = await this.iniciarSesionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
