/* tslint:disable */
/* eslint-disable */
/**
 * Aula Viva API
 * API REST de Aula Viva para autenticación, consulta de aulas, consulta de alumnos y creación idempotente de invitaciones. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InvitacionReplayResponse,
    InvitacionReplayResponseFromJSON,
    InvitacionReplayResponseToJSON,
} from '../models/InvitacionReplayResponse';
import {
    type InvitacionRequest,
    InvitacionRequestFromJSON,
    InvitacionRequestToJSON,
} from '../models/InvitacionRequest';
import {
    type InvitacionResponse,
    InvitacionResponseFromJSON,
    InvitacionResponseToJSON,
} from '../models/InvitacionResponse';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface CrearInvitacionRequest {
    /**
     * Clave única proporcionada por el cliente para evitar que un reintento cree una segunda invitación.
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    invitacionRequest: InvitacionRequest;
}

/**
 * 
 */
export class InvitacionesApi extends runtime.BaseAPI {

    /**
     * Creates request options for crearInvitacion without sending the request
     */
    async crearInvitacionRequestOpts(requestParameters: CrearInvitacionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling crearInvitacion().'
            );
        }

        if (requestParameters['invitacionRequest'] == null) {
            throw new runtime.RequiredError(
                'invitacionRequest',
                'Required parameter "invitacionRequest" was null or undefined when calling crearInvitacion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }


        let urlPath = `/invitaciones`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvitacionRequestToJSON(requestParameters['invitacionRequest']),
        };
    }

    /**
     * Crea una invitación de manera idempotente. Si se repite una solicitud con la misma Idempotency-Key, la API devuelve la invitación creada anteriormente en vez de crear una nueva. 
     * Crear una invitación
     */
    async crearInvitacionRaw(requestParameters: CrearInvitacionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitacionReplayResponse>> {
        const requestOptions = await this.crearInvitacionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitacionReplayResponseFromJSON(jsonValue));
    }

    /**
     * Crea una invitación de manera idempotente. Si se repite una solicitud con la misma Idempotency-Key, la API devuelve la invitación creada anteriormente en vez de crear una nueva. 
     * Crear una invitación
     */
    async crearInvitacion(requestParameters: CrearInvitacionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitacionReplayResponse> {
        const response = await this.crearInvitacionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
